name: Build QMK firmware

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ae0d588378c528a97635c7dc4345fff2a2ff5dac
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@ae0d588378c528a97635c7dc4345fff2a2ff5dac
    if: always() && !cancelled() && github.event_name != 'pull_request'
    needs: build
