name: Build QMK firmware

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ae0d588378c528a97635c7dc4345fff2a2ff5dac
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial

  attest:
    name: 'QMK Userspace Attest'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    permissions:
      actions: read
      attestations: write
      contents: read
      id-token: write

    steps:
      - name: Download binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Firmware

      - name: Attest firmware artifacts
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: |
            *.bin
            *.hex
            *.uf2

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@ae0d588378c528a97635c7dc4345fff2a2ff5dac
    if: needs.attest.result == 'success' && github.event_name != 'pull_request'
    needs: [build, attest]
